# Generated by Django 3.2 on 2021-04-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title of the tour')),
                ('desc', models.TextField(verbose_name='Description of the tour')),
            ],
        ),
    ]
