# Generated by Django 3.2 on 2021-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kaztour_tourcart_tourcartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaztour',
            name='category_slug',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
