# Generated by Django 3.2 on 2021-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210427_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.TextField(null=False, default='None', verbose_name='Image link'),
            preserve_default=False,
        ),
    ]
